project:
  type: website
  output-dir: docs
  
website:
  title: "Tweety's website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




